spring:
  profiles: prod
  datasource:
    url: jdbc:mariadb://localhost:3306/testdb
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: false