spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${url}
    driver-class-name: org.mariadb.jdbc.Driver
    username: ${username}
    password: ${password}
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true