gemini:
  api:
    key: ${GEMINI_API_KEY}
  model:
    name: "gemini-2.5-flash-lite-preview-06-17"
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: ${url}
    driver-class-name: org.mariadb.jdbc.Driver
    username: dotg
    password: dotg0527
  jpa:
    open-in-view: false
    hibernate:
      default_batch_fetch_size: 10
      ddl-auto: update
      #ddl-auto: create-drop
      type:
        descriptor:
          #sql: trace
    properties:
      hibernate:
        format_sql: false
        show-sql: false
        auto_quote_keyword: false
  kafka:
      bootstrap-servers: localhost:9092
      producer:
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.apache.kafka.common.serialization.StringSerializer
      consumer:
        group-id: topic-group-01
        auto-offset-reset: earliest
        key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
        value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      logging:
        level:
          org.springframework.web.client: INFO
          org.hibernate: OFF
          org.hibernate.SQL: OFF
          org.hibernate.type.descriptor.sql.BasicExtractor: OFF
          org.hibernate.type.descriptor.sql.BasicBinder: OFF