spring:
  profiles:
    active: dev
  redis:
    host: localhost
    port: 6379
  flyway:
    enabled: false

jwt:
  secret-key: ^YjwtAQSecretKey123!@$(*&^YveryYYYDDDZSecret84356@#@^#imp!!@1512why$%^$*%(^^%&So35!@@@%!@#$Long

server:
  port: 29929

# 로그 레벨 설정
logging:
  level:
    # hibernate 가 남기는 모든 로그가 debug모드로 설정
    # jpa hibernate가 생성하는 sql이 로거를 통해서 찍히도록 하는 설정
    org.hibernate.SQL: trace #trace
    org.hibernate.type: trace # 실제 들어가는 파라미터값 찍어주는 설정